### ISSUE TITLE
new look-up algorithm for link checking

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/linkchecker-persistence#3]
The Spout of the linkchecker application requires a set of URLs which it injects to the processing chain. Currently it calls a method in linkchecker-persistence which sends one large, time consuming SQL query to the underlying linkchecker database. Hence the current look-up algorithm isn't more than this query. 
The query itself groups the URLs by host and orders them within each group by priority-flag and checking_date desc with non checked links at the beginning of the order. Further on it takes the first n URLs of each group. Out of this it takes the first m URLs in total. 

the new look-up algorithm has to archive multiple goals: 

1. to assure a parallel link checking by host. This means each look-up has to return a set of URLs with at least as many many different hosts as we have parallel threads for link checking
2. to allow certain prioritization of URLs for link checking. This requirement concerns basically the links/URLs added by the linkchecker API (project: linkchecker-web) 
3. to speed up the look-up process

Possible solution: 

1. adding an int field priority to the url table with a default value of 0 and some int value for any prioritization
2. adding a new table next_check with fields id and url_id. This allows us to decouple the time consuming look-up process from the reading process: reading the content of the next_check table could trigger a lookup-thread at the end to fill up the table again

**Comment by twagoo** [comment]
Do we have any specific requirements or constraints for the process in which this look-up takes place? E.g. do we need to have 'iterations' in which we populate all the "workers" (parallel threads), or could it be something more sophisticated such as a solution based on a stream from which links are pulled constantly by each of the threads with a mechanism to reject a link based on condition such as whether that host is already being checked in another thread, and whether checking now is allowed by robots.txt rules.

Perhaps a filtered stream using R2DBC ([supported in Spring it seems](https://mariadb.com/docs/skysql/connect/programming-languages/java-r2dbc/spring/)) could be the basis for a solution.

**Comment by wowasa** [comment]
First off all workers and threads are two different things in Apache Storm: we can have multiple workers and multiple threads per worker. As far as a understand it there is even one level in between: a worker manages one processing chain, which has one or multiple instances of Spouts and Bolts while each of them can have multiple threads.  
The threads in the linkchecker application (in terms of Storm "topology") are created and managed by the MetricsFetcherBolt. As far as I understand the concept of Apache Storm, it's not the idea of a Bolt to pull anything. It's the Spout, which pushes. 
Therefore, what I understand is, that the Spout injects the URLs into the processing chain and the MetricsFetcherBolt assures a parallel checking by host, while the number of threads is configured

**Comment by wowasa** [comment]
> Perhaps a filtered stream using R2DBC ([supported in Spring it seems](https://mariadb.com/docs/skysql/connect/programming-languages/java-r2dbc/spring/)) could be the basis for a solution.

actually I would prefer to have more than just a keyword

**Comment by wowasa** [comment]
added field priority to url table. I'm dropping the approach of adding a table for the moment since I could speed up the link checking significantly by modifying the properties
